### ISSUE TITLE
[BUG] Fix Hyperlane Interchain Gas Fee

### ISSUE THREAD

**Issue by devpavan04** [tangle-network/dapp#2583]
### Overview

Currently, the interchain gas fee for a Hyperlane bridge transfer is displayed as 0. We're using Hyperlane SDK's `warpCore.estimateTransferRemoteFees()` to obtain gas estimates. The 0 interchain gas fee may be due to the Hyperlane core configuration on both the `Holesky` and `Tangle Testnet`, which uses a 0 protocol fee. However, further investigation is required before closing this issue.

![CleanShot 2024-10-11 at 11 28 19](https://github.com/user-attachments/assets/cef96312-e9a0-468b-a7b2-66d8bc55bc5b)

```yaml
requiredHook:
  beneficiary: "0x009928463436d9CFf320d4E9E0D36376c71C1C1E"
  maxProtocolFee: "100000000000000000"
  owner: "0x009928463436d9CFf320d4E9E0D36376c71C1C1E"
  protocolFee: "0"
  type: protocolFee
```
